### ISSUE TITLE
Request to add installation guide for Ebyte gateways

### ISSUE THREAD

**Issue by Limerin555** [chirpstack/chirpstack-mqtt-forwarder#36]
Could you kindly add Ebyte (model E890-915LG12) as one of the gateway vendors to your installation guide. Thank you.

**Comment by brocaar** [comment]
@Limerin555 do you have any technical details about this gateway?

From the manual screenshots, it looks like the firmware is OpenWRT based. But I could not find any information about the architecture.

Could you post the output of the following commands:

* `cat /proc/cpuinfo`
* `df -h`
* `mount`

**Comment by brocaar** [comment]
I'm closing this issue as no further details were provided.
