### ISSUE TITLE
Bug: Default configuration on install ipk is invalid

### ISSUE THREAD

**Issue by devleesch001** [chirpstack/chirpstack-mqtt-forwarder#48]
# Probleme

When I install the last ipk `4.1.3` the default file of configuration have an field with wrong key.

Default configuration is :  
```
[backend]
  enabled="semtech_udp" 

  [backend.semtech_udp]
    udp_bind="0.0.0.0:1700"
```
and doest work.

But in documentation the exemple is 

```
[backend]
  enabled="semtech_udp" 

  [backend.semtech_udp]
    bind="0.0.0.0:1700"
```

# Fix 

Change at line 12 in file chirpstack-mqtt-forwarder.toml `udp_bind="0.0.0.0:1700"` to `bind="0.0.0.0:1700"`

**Comment by brocaar** [comment]
Yes, you are right, this should have been `bind` instead of `udp_bind`:
https://github.com/chirpstack/chirpstack-mqtt-forwarder/blob/master/src/config.rs#L141
