### ISSUE TITLE
Implement max_reconnect_interval setting like Chirpstack Gateway Bridge

### ISSUE THREAD

**Issue by paill0u** [chirpstack/chirpstack-mqtt-forwarder#51]
Hello !

Would it be possible to implement a **max_reconnect_interval** setting like it use to behave for Chirpstack Gateway Bridge ?

The MQTT broker provider I'm using has a strict rule of services restart every day, which makes the Chirpstack MQTT forwarder give up at some point not trying to reconnect.

Thanks a lot in advance for your consideration !

**Comment by brocaar** [comment]
With the migration to rumqttc this is no longer relevant, on error it will retry after 1 second. Please see the v4.2.0 release
