### ISSUE TITLE
MQTT Forwarder request for MikroTik

### ISSUE THREAD

**Issue by Sleeper67** [chirpstack/chirpstack-mqtt-forwarder#55]
Hello,

this is a request for an MQTT forwarder to suit the MikroTik Gateways please.

Specifically RBwAPR-2nD_R11e-LoRa9

Thanks

**Comment by Sleeper67** [comment]
Hi Orne,

ok thanks, please let me check with MikroTik and my distributor. I do know they have on some of their routerOS v7 and above  the ability to host Docker but will see if the LoRa specific Gateways can do this. 

I thought you can SSH into it but let me report back .

Cheers

**Comment by brocaar** [comment]
Do you have any update on this? Else I will close this issue.

**Comment by Sleeper67** [comment]
Hi Orne,

Apologies for the delay in getting back to this,

Theres also the  ability with v7 to run docker containers, just not sure on if there's enough disk on MikroTik WAP8 or WAP9.
https://help.mikrotik.com/docs/display/ROS/Container

RouterOS only has built-in MQTT functionality using:
https://help.mikrotik.com/docs/display/ROS/MQTT

**Comment by brocaar** [comment]
> Container package is compatible with arm arm64 and x86 architectures. Using of remote-image (similar to docker pull) functionality requires a lot of free space in main memory, 16MB SPI flash boards may use pre-build images on USB or other disk media.

The WAP8 and WAP9 are MIPS, so I don't think this will be an option.

**Comment by Sleeper67** [comment]
Thanks Orne!

no problem, we got basic station working on it instead. So you can close this issue.

Also regarding ssh on how into MikroTik I have attached the CLI
![Screenshot 2024-05-10 at 11 11 36 PM](https://github.com/chirpstack/chirpstack-mqtt-forwarder/assets/69107925/cf0109d3-6ace-42e3-a2ab-cbc34c9b779a)

**Comment by brocaar** [comment]
> Also regarding ssh on how into MikroTik I have attached the CLI

I also managed to SSH into the gateway before, but it only provided me with a CLI shell to configure MikroTik parameters, eg. I was unable to get access to a bash-like shell where I could execute just any command.
