### ISSUE TITLE
MQTT Forwarder request for Milesight

### ISSUE THREAD

**Issue by karaboLindiwe** [chirpstack/chirpstack-mqtt-forwarder#56]
Hello,

this is a request for an MQTT forwarder to suit the Milesight Gateways please.

**Comment by brocaar** [comment]
As far as I'm aware of, Milesight does not offer the option to install
additional packages on the gateway.

**Comment by brocaar** [comment]
Please see https://www.chirpstack.io/docs/gateway-configuration/milesight.html
