### ISSUE TITLE
Milesigth

### ISSUE THREAD

**Issue by BenjaSar** [chirpstack/chirpstack-mqtt-forwarder#58]
Hi there,

In our company, we are working with the  gateway Milesight UG67. Please, could you add the Chirpstack MQTT  forwarder for this brand?.

**Comment by brocaar** [comment]
Have you seen
https://www.chirpstack.io/docs/gateway-configuration/milesight.html ?

**Comment by BenjaSar** [comment]
Hi @brocaar , 

Thank you so much for your quick response.  I will review the link shared by you.

Best wishes.

**Comment by brocaar** [comment]
I'm closing this issue as there is nothing that I can do from my side as Milesight does not allow installing custom packages.
